addons:
  artifacts: true
  code_climate:
    repo_token: ca5e6c667335156dd53cb3e507e68552a9392be4242a3b5895e83c69d4f77891
language: node_js
node_js:
  - "6"
before_script:
  - npm install -g babel-cli
  - psql -c 'create database travis_ci_test;' -U postgres
before_deploy:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: 0997c645-d9fe-49be-ac06-4cb1a2e53cfd
  app: manage-document
  skip_cleanup: true
  on:
    all_branches: true
services:
  - postgresql
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info