addons:
  artifacts: true
  code_climate:
    repo_token: 11ea769c4665484272290c541893b6e7c2d304761b8962f4a5956b8fd1586fc7
language: node_js
node_js:
  - "6"
before_script:
  - npm install -g babel-cli
  - psql -c 'create database travis_ci_test;' -U postgres
before_deploy:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: 0997c645-d9fe-49be-ac06-4cb1a2e53cfd
  app: manage-document
  skip_cleanup: true
  on:
    all_branches: true
services:
  - postgresql
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info