export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const CREATE_ROLES_SUCCESS = 'CREATE_ROLES_SUCCESS';
export const SHOW_EDITABLE_ROLE = 'SHOW_EDITABLE_ROLE';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_PUBLIC_DOCUMENTS_SUCCESS = 'GET_PUBLIC_DOCUMENTS_SUCCESS';
export const GET_ROLE_DOCUMENTS_SUCCESS = 'GET_ROLE_DOCUMENTS_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const CREATE_DOCUMENTS_SUCCESS = 'CREATE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = 'DELETE_DOCUMENTS_SUCCESS';
export const SHOW_DOCUMENT = 'SHOW_DOCUMENT';
export const NEW_DOCUMENT = 'NEW_DOCUMENT';
export const EDIT_USER = 'EDIT_USER';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const SHOW_DOC_COMPONENT = 'SHOW_DOC_COMPONENT';
export const SHOW_USER_COMPONENT = 'SHOW_USER_COMPONENT';
export const SHOW_ROLE_COMPONENT = 'SHOW_ROLE_COMPONENT';


